--SELECT * FROM employees
--COPY employees FROM '\Users\Sahil Rajapkar\Desktop\Employees123.csv' WITH (FORMAT csv);
--SELECT * FROM employees

/*************************************************************
SELECT FIRSTNAME,
LASTNAME,
GENDER, 
TITLE
FROM EMPLOYEES
WHERE GENDER = 'F'
AND TITLE = 'Marketing Assistant'
**************************************************************/

/*************************************************************
SELECT FIRSTNAME,
LASTNAME,
TITLE,
HIREDATE, 
SALARY,
ACTIVE,
GENDER,
MARITALSTATUS
FROM EMPLOYEES 
WHERE HIREDATE::date >= '01/01/2000'
AND SALARY >= '50000'
AND ACTIVE = 'Yes'
AND GENDER = 'F'
AND MARITALSTATUS = 'M'
ORDER BY SALARY
**************************************************************/

/*************************************************************

SELECT FIRSTNAME,
LASTNAME,
GENDER,
VACATIONHOURS,
SICKLEAVEHOURS
FROM EMPLOYEES
WHERE (VACATIONHOURS > 90
OR SICKLEAVEHOURS < 5)
AND UPPER(GENDER) = 'M'
ORDER BY VACATIONHOURS, SICKLEAVEHOURS

SELECT FIRSTNAME F_NAME, LASTNAME L_NAME, 3 + 5 TOTAL 
CONVERT(VACATIONHOURS, INT)
FROM EMPLOYEES

**************************************************************/

/****** RUN ALL THESE LATER
SELECT FIRSTNAME F_NAME, LASTNAME L_NAME, 
VACATIONHOURS, SICKLEAVEHOURS
CAST(VACATIONHOURS AS INTEGER) + (SICKLEAVEHOURS AS INTEGER) TOTAL_PTO
FROM EMPLOYEES
SELECT FIRSTNAME,
LASTNAME,
TITLE,
HIREDATE,
SALARY

FROM EMPLOYEES
WHERE UPPER(TITLE) = 'ENGINEERING MANAGER'
OR UPPER(TITLE) = 'DESIGN ENGINEER'
OR UPPER(TITLE) = 'SCHEDULING ASSISTANT'
OR UPPER(TITLE) = 'APPLICATION SPECIALIST'
ORDER BY TITLE


SELECT FIRSTNAME,
LASTNAME,
TITLE,
HIREDATE,
SALARY
FROM EMPLOYEES
WHERE UPPER(TITLE) IN ('ENGINEERING MANAGER', 'DESIGN ENGINEER', 'SCHEDULING ASSISTANT','APPLICATION SPECIALIST')
ORDER BY TITLE

SELECT FIRSTNAME,
LASTNAME,
TITLE,
HIREDATE,
SALARY
FROM EMPLOYEES
WHERE UPPER(TITLE) NOT IN ('ENGINEERING MANAGER', 'DESIGN ENGINEER', 'SCHEDULING ASSISTANT','APPLICATION SPECIALIST')
ORDER BY TITLE
******/

/*****
SELECT FIRSTNAME,
LASTNAME,
TITLE,
HIREDATE,
SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN '56099.98' AND '66299.98'
ORDER BY SALARY
************/ 

SELECT FIRSTNAME,
LASTNAME,
TITLE,
HIREDATE,
SALARY
FROM EMPLOYEES
WHERE HIREDATE BETWEEN '1997/12/12' AND '1998/03/03'
--THIS ALSO TAKES IN SLASHES FOR DATES--

SS