--SELECT * FROM ADDRESS
--WHERE DISTRICT > ''
--AND (UPPER(DISTRICT) = 'ABU DHABI' OR CITY_ID = 3)
--OR POSTAL_CODE = '69221'
--ORDER BY DISTRICT

--SELECT DISTINCT DISTRICT FROM ADDRESS 
--ORDER BY DISTRICT

--SELECT * FROM ADDRESS
--WHERE DISTRICT = 'Abu Dhabi'

--SELECT * FROM ADDRESS 
--WHERE DISTRICT = 'Abu Dhabi' AND CITY_ID = 3

--SELECT * FROM ACTOR
/*
--INSERT INTO ACTOR (FIRST_NAME, LAST_NAME) VALUES ('Thomas','Smith')
--**NOTE RUN INSERT FIRST THEN SLECT**
*/

SELECT * FROM ACTOR
WHERE LAST_NAME = 'O''Brien'
INSERT INTO ACTOR (FIRST_NAME, LAST_NAME) VALUES ('Robert','O''Brien')